Music.add_music("ゆず", "サヨナラバス")
Music.add_music("ゆず", "夏色")
Music.add_music("ゆず", "桜木町")
Music.add_music("大塚愛", "PEACH")
Music.add_music("いきものがかり", "気まぐれロマンティック")
Music.add_music("いきものがかり", "ありがとう")
Music.add_music("Superfly", "愛をこめて花束を")
